before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
build:
  image: docker:latest
  variables:
    DOCKER_DRIVER: overlay2
  services:
    - docker:dind
  only:
    - master
    - tags
  script:
    - "docker build --pull -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME ."
    - "docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME"
